---
- name: Install docker dependencies
  package:
    name: "{{item}}"
    state: latest
  become: yes
  with_items:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
  become: yes
  
- name: Install docker
  package:
    name: docker-ce
    state: latest
  become: yes